In [20]:
# [
#  [1000, 2],
#  [1500, 3],
# ]

import numpy as np

def matrix_std():
    # numpy matrix representation   
    matrix = np.array([[1000,2],[1500,3]])
    
    # max & min elements vertically
    max_elements = list()
    min_elements = list()
    for column in matrix:
        min_value = column[0]
        max_value = column[0]
        for item in column:
            min_value = min(item, min_value)
            max_value = max(item, max_value)
        max_elements.append(max_value)
        min_elements.append(min_value)
    
    # ranges
    ranges = list()
    for i in range(len(max_elements)):
        ranges.append(max_elements[i]-min_elements[i])
    print(ranges)
    
    # create matrix std
    matrix_std = list()
    col = list()
    for i in range(len(matrix)):
        for item in matrix:
            std_item = matrix[i]-min_elements[i] // ranges[i]
            col.append(std_item)
            matrix_std.append(col)
    
    return matrix_std
    
matrix_std()

[998, 1497]


[[array([1000,    2]),
  array([1000,    2]),
  array([1500,    3]),
  array([1500,    3])],
 [array([1000,    2]),
  array([1000,    2]),
  array([1500,    3]),
  array([1500,    3])],
 [array([1000,    2]),
  array([1000,    2]),
  array([1500,    3]),
  array([1500,    3])],
 [array([1000,    2]),
  array([1000,    2]),
  array([1500,    3]),
  array([1500,    3])]]

In [6]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X_train)
print(X_minmax)

NameError: name 'X_train' is not defined